//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActiveReflactorClient.ActivationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer", ConfigurationName="ActivationServiceReference.ActivationSoap")]
    public interface ActivationSoap {
        
        // CODEGEN: Generating message contract since element name serialNumber from namespace http://red-gate.com/webservices/ActivationServer is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://red-gate.com/webservices/ActivationServer/GetSerialCreated", ReplyAction="*")]
        ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedResponse GetSerialCreated(ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequest request);
        
        // CODEGEN: Generating message contract since element name serialNumber from namespace http://red-gate.com/webservices/ActivationServer is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://red-gate.com/webservices/ActivationServer/GetSupportExpiry", ReplyAction="*")]
        ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryResponse GetSupportExpiry(ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequest request);
        
        // CODEGEN: Generating message contract since element name serialNumber from namespace http://red-gate.com/webservices/ActivationServer is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://red-gate.com/webservices/ActivationServer/GetActivationsRemaining", ReplyAction="*")]
        ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingResponse GetActivationsRemaining(ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequest request);
        
        // CODEGEN: Generating message contract since element name activationRequest from namespace http://red-gate.com/webservices/ActivationServer is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://red-gate.com/webservices/ActivationServer/ActivateLicence", ReplyAction="*")]
        ActiveReflactorClient.ActivationServiceReference.ActivateLicenceResponse ActivateLicence(ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequest request);
        
        // CODEGEN: Generating message contract since element name deactivationRequest from namespace http://red-gate.com/webservices/ActivationServer is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://red-gate.com/webservices/ActivationServer/DeactivateLicence", ReplyAction="*")]
        ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceResponse DeactivateLicence(ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSerialCreatedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSerialCreated", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequestBody Body;
        
        public GetSerialCreatedRequest() {
        }
        
        public GetSerialCreatedRequest(ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetSerialCreatedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productCode;
        
        public GetSerialCreatedRequestBody() {
        }
        
        public GetSerialCreatedRequestBody(string serialNumber, int productCode) {
            this.serialNumber = serialNumber;
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSerialCreatedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSerialCreatedResponse", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedResponseBody Body;
        
        public GetSerialCreatedResponse() {
        }
        
        public GetSerialCreatedResponse(ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetSerialCreatedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime GetSerialCreatedResult;
        
        public GetSerialCreatedResponseBody() {
        }
        
        public GetSerialCreatedResponseBody(System.DateTime GetSerialCreatedResult) {
            this.GetSerialCreatedResult = GetSerialCreatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupportExpiryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupportExpiry", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequestBody Body;
        
        public GetSupportExpiryRequest() {
        }
        
        public GetSupportExpiryRequest(ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetSupportExpiryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        public GetSupportExpiryRequestBody() {
        }
        
        public GetSupportExpiryRequestBody(string serialNumber) {
            this.serialNumber = serialNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSupportExpiryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSupportExpiryResponse", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryResponseBody Body;
        
        public GetSupportExpiryResponse() {
        }
        
        public GetSupportExpiryResponse(ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetSupportExpiryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime GetSupportExpiryResult;
        
        public GetSupportExpiryResponseBody() {
        }
        
        public GetSupportExpiryResponseBody(System.DateTime GetSupportExpiryResult) {
            this.GetSupportExpiryResult = GetSupportExpiryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivationsRemainingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivationsRemaining", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequestBody Body;
        
        public GetActivationsRemainingRequest() {
        }
        
        public GetActivationsRemainingRequest(ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetActivationsRemainingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int productCode;
        
        public GetActivationsRemainingRequestBody() {
        }
        
        public GetActivationsRemainingRequestBody(string serialNumber, int productCode) {
            this.serialNumber = serialNumber;
            this.productCode = productCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActivationsRemainingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActivationsRemainingResponse", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingResponseBody Body;
        
        public GetActivationsRemainingResponse() {
        }
        
        public GetActivationsRemainingResponse(ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class GetActivationsRemainingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetActivationsRemainingResult;
        
        public GetActivationsRemainingResponseBody() {
        }
        
        public GetActivationsRemainingResponseBody(int GetActivationsRemainingResult) {
            this.GetActivationsRemainingResult = GetActivationsRemainingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateLicenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateLicence", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequestBody Body;
        
        public ActivateLicenceRequest() {
        }
        
        public ActivateLicenceRequest(ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class ActivateLicenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string activationRequest;
        
        public ActivateLicenceRequestBody() {
        }
        
        public ActivateLicenceRequestBody(string activationRequest) {
            this.activationRequest = activationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActivateLicenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActivateLicenceResponse", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.ActivateLicenceResponseBody Body;
        
        public ActivateLicenceResponse() {
        }
        
        public ActivateLicenceResponse(ActiveReflactorClient.ActivationServiceReference.ActivateLicenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class ActivateLicenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ActivateLicenceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string activationResponse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errorMessage;
        
        public ActivateLicenceResponseBody() {
        }
        
        public ActivateLicenceResponseBody(bool ActivateLicenceResult, string activationResponse, string errorMessage) {
            this.ActivateLicenceResult = ActivateLicenceResult;
            this.activationResponse = activationResponse;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactivateLicenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactivateLicence", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequestBody Body;
        
        public DeactivateLicenceRequest() {
        }
        
        public DeactivateLicenceRequest(ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class DeactivateLicenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string deactivationRequest;
        
        public DeactivateLicenceRequestBody() {
        }
        
        public DeactivateLicenceRequestBody(string deactivationRequest) {
            this.deactivationRequest = deactivationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeactivateLicenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeactivateLicenceResponse", Namespace="http://red-gate.com/webservices/ActivationServer", Order=0)]
        public ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceResponseBody Body;
        
        public DeactivateLicenceResponse() {
        }
        
        public DeactivateLicenceResponse(ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://red-gate.com/webservices/ActivationServer")]
    public partial class DeactivateLicenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeactivateLicenceResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errorMessage;
        
        public DeactivateLicenceResponseBody() {
        }
        
        public DeactivateLicenceResponseBody(bool DeactivateLicenceResult, string errorMessage) {
            this.DeactivateLicenceResult = DeactivateLicenceResult;
            this.errorMessage = errorMessage;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivationSoapChannel : ActiveReflactorClient.ActivationServiceReference.ActivationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivationSoapClient : System.ServiceModel.ClientBase<ActiveReflactorClient.ActivationServiceReference.ActivationSoap>, ActiveReflactorClient.ActivationServiceReference.ActivationSoap {
        
        public ActivationSoapClient() {
        }
        
        public ActivationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedResponse ActiveReflactorClient.ActivationServiceReference.ActivationSoap.GetSerialCreated(ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequest request) {
            return base.Channel.GetSerialCreated(request);
        }
        
        public System.DateTime GetSerialCreated(string serialNumber, int productCode) {
            ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequest inValue = new ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequest();
            inValue.Body = new ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.productCode = productCode;
            ActiveReflactorClient.ActivationServiceReference.GetSerialCreatedResponse retVal = ((ActiveReflactorClient.ActivationServiceReference.ActivationSoap)(this)).GetSerialCreated(inValue);
            return retVal.Body.GetSerialCreatedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryResponse ActiveReflactorClient.ActivationServiceReference.ActivationSoap.GetSupportExpiry(ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequest request) {
            return base.Channel.GetSupportExpiry(request);
        }
        
        public System.DateTime GetSupportExpiry(string serialNumber) {
            ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequest inValue = new ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequest();
            inValue.Body = new ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryRequestBody();
            inValue.Body.serialNumber = serialNumber;
            ActiveReflactorClient.ActivationServiceReference.GetSupportExpiryResponse retVal = ((ActiveReflactorClient.ActivationServiceReference.ActivationSoap)(this)).GetSupportExpiry(inValue);
            return retVal.Body.GetSupportExpiryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingResponse ActiveReflactorClient.ActivationServiceReference.ActivationSoap.GetActivationsRemaining(ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequest request) {
            return base.Channel.GetActivationsRemaining(request);
        }
        
        public int GetActivationsRemaining(string serialNumber, int productCode) {
            ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequest inValue = new ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequest();
            inValue.Body = new ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.productCode = productCode;
            ActiveReflactorClient.ActivationServiceReference.GetActivationsRemainingResponse retVal = ((ActiveReflactorClient.ActivationServiceReference.ActivationSoap)(this)).GetActivationsRemaining(inValue);
            return retVal.Body.GetActivationsRemainingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveReflactorClient.ActivationServiceReference.ActivateLicenceResponse ActiveReflactorClient.ActivationServiceReference.ActivationSoap.ActivateLicence(ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequest request) {
            return base.Channel.ActivateLicence(request);
        }
        
        public bool ActivateLicence(string activationRequest, out string activationResponse, out string errorMessage) {
            ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequest inValue = new ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequest();
            inValue.Body = new ActiveReflactorClient.ActivationServiceReference.ActivateLicenceRequestBody();
            inValue.Body.activationRequest = activationRequest;
            ActiveReflactorClient.ActivationServiceReference.ActivateLicenceResponse retVal = ((ActiveReflactorClient.ActivationServiceReference.ActivationSoap)(this)).ActivateLicence(inValue);
            activationResponse = retVal.Body.activationResponse;
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.ActivateLicenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceResponse ActiveReflactorClient.ActivationServiceReference.ActivationSoap.DeactivateLicence(ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequest request) {
            return base.Channel.DeactivateLicence(request);
        }
        
        public bool DeactivateLicence(string deactivationRequest, out string errorMessage) {
            ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequest inValue = new ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequest();
            inValue.Body = new ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceRequestBody();
            inValue.Body.deactivationRequest = deactivationRequest;
            ActiveReflactorClient.ActivationServiceReference.DeactivateLicenceResponse retVal = ((ActiveReflactorClient.ActivationServiceReference.ActivationSoap)(this)).DeactivateLicence(inValue);
            errorMessage = retVal.Body.errorMessage;
            return retVal.Body.DeactivateLicenceResult;
        }
    }
}
